version: '3'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/eventgo
      - JWT_SECRET=production_jwt_secret_change_me
      - PORT=5001
      - WEB3_PROVIDER=http://localhost:8545
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/eventGo/frontend/node_modules
      - /usr/src/app/eventGo/backend/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 